---
- name: "Prepare"
  hosts: all
  become: true
  tasks:
    - name: "Install pre-requisites for molecule tests (Debian)"
      ansible.builtin.package:
        name:
          - cron
        state: present
        update_cache: true
      when: ansible_os_family in ['Debian', 'Ubuntu']

    - name: "Install pre-requisites for molecule tests (RedHat)"
      ansible.builtin.package:
        name:
          - cronie
          - epel-release
        state: present
        update_cache: true
      when: ansible_os_family == 'RedHat'

    - name: "Install pip"
      ansible.builtin.include_role:
        name: geerlingguy.pip

    # Required for molecule testing images to have an up-to-date pyopenssl
    - name: "Install pyopenssl"
      ansible.builtin.pip:
        name: pyopenssl
        state: latest
      tags:
        - skip_ansible_lint
