---
- name: "Prepare"
  hosts: all
  become: true
  vars:
    # Disable setting up renewal cronjob by geerlingguy.certbot
    certbot_auto_renew: false
    certbot_install_method: "snap"
  tasks:
    - name: "Update package cache"
      ansible.builtin.package:
        update_cache: true

    - name: "Install snapd"
      ansible.builtin.apt:
        name:
          - snapd
        state: present

    - name: "List service facts"
      ansible.builtin.service_facts:

    # This is required to work around an "too early for operations" error
    # when using snapd directly after installation
    - name: "Ensure snapd seeded service is restarted."
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      when: "item in ansible_facts.services"
      with_items:
        - snapd.service
        - snapd.seeded.service
        - systemd-udevd.service

    - name: "Install pre-requisites for molecule tests (RedHat)"
      ansible.builtin.package:
        name:
          - epel-release
        state: present
      when: ansible_os_family == 'RedHat'

    - name: "Install pip"
      ansible.builtin.include_role:
        name: geerlingguy.pip

    - name: "Install pyopenssl"
      ansible.builtin.pip:
        name:
          - pyopenssl
        # Required for molecule testing images to have an up-to-date pyopenssl
        state: latest
      tags:
        - skip_ansible_lint
      when:
        - ansible_os_family == 'Debian'
        - ansible_facts['distribution_major_version'] | int < 12

    - name: "Install Certbot from package manager"
      ansible.builtin.include_role:
        name: geerlingguy.certbot

    - name: "Create certificate directory for placing fake directory"
      ansible.builtin.file:
        path: /etc/letsencrypt/live/example.com/cert
        state: directory
        owner: root
        group: root
        mode: "0644"

    - name: "Place a fake certificate so the role thinks the certificate already exists"
      ansible.builtin.file:
        path: /etc/letsencrypt/live/example.com/cert.pem
        state: touch
        owner: root
        group: root
        mode: "0644"
