---
- name: "Prepare"
  hosts: all
  become: true
  vars:
    # Disable setting up renewal cronjob by geerlingguy.certbot
    certbot_auto_renew: false
  tasks:
    - name: "Update package cache"
      ansible.builtin.package:
        update_cache: true

    - name: "Install pre-requisites for molecule tests (RedHat)"
      ansible.builtin.package:
        name:
          - epel-release
        state: present
      when: ansible_os_family == 'RedHat'

    - name: "Install pip"
      ansible.builtin.include_role:
        name: geerlingguy.pip

    # Required for molecule testing images to have an up-to-date pyopenssl
    - name: "Install pyopenssl"
      ansible.builtin.pip:
        name:
          - pyopenssl
        state: latest
      tags:
        - skip_ansible_lint

    - name: "Install Certbot from package manager"
      ansible.builtin.include_role:
        name: geerlingguy.certbot

    - name: "Create certificate directory for placing fake directory"
      ansible.builtin.file:
        path: /etc/letsencrypt/live/example.com/cert
        state: directory
        owner: root
        group: root
        mode: "0644"

    - name: "Place a fake certificate so the role thinks the certificate already exists"
      ansible.builtin.file:
        path: /etc/letsencrypt/live/example.com/cert.pem
        state: touch
        owner: root
        group: root
        mode: "0644"
